services:
- postgresql
addons:
  postgresql: '9.4'
language: elixir
elixir:
- 1.3.4
env:
- MIX_ENV=test
notifications:
  slack:
    secure: F+R3x8Q4UlYtK56+xoXdCBPIntXZ39QOogD8bvGqbPUhC+Mk+QZ9TlTIYa5ZLZb+Vy/Njnx8mlNlJmWkCtmtel7ShqCsGnbdvLOP4fu33jx7XWm23AFavcBZshwDQPBZdEovlW0uB7evd2X2sLS74VfaJIZq6bnwtHBUth6OWDAJaFa5cZDuScciAsEDbbEncqnu2GmWIIrrM4u36xAtfHaURKAKmY3exCsF6MfVtLwQeNsVqXfMuDiTYI6+hTevgARaLlRU/dw4xl54RpQpAfF2ddPXh/ck4aa0F7GWK6wmjL6E5XEDsif16gtIUwUNUb2kuUEGsJ1e56KRqQG1D/CAgWdPlNlseRGbg8WifK/mIRD5/aeol1DAT0t23KP7AKlDxHT8q7YxjxdO6cb3h9Za15X7B5/2HoYZT5DD9bFB6JNRJqCNWg93058FiEerBmFkAaMvN2X1UoKjG8Yo051vrGGXoH9fGNvY3Tuk/hsLw1qyL8uo1EcF49hIZc+r9cv6NbrpVWw5eY2dhqTEEzWDkiAZ+KQZDLKWnM4HiHPq49Kw4c8Bpa9imWIqoBjdn8FniO7SqaqXjvWM3sSMZ3tESqv9vDqF4ZvTIIw518Ofc34skFj2xGbTVl3L1UW6L9Ums2SWVmMIBzSyrvEOnGodWRZ6PRYsAYhklK9+9zA=
before_script:
- mix do ecto.create, ecto.migrate
script:
- mix test
